apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wasp-ingest-ttn.fullname" . }}-config
  labels:
    {{- include "wasp-ingest-ttn.labels" . | nindent 4 }}
data:
  waspIngestTtnPort: {{ .Values.config.waspIngestTtnPort | quote }}
  redisHost: {{ include "wasp-ingest-ttn.redis.fullname" . }}
  redisPort: {{ .Values.config.redisPort | quote }}
  redisUsername: {{ include "wasp-ingest-ttn.redis.username" . }}
  redisTlsEnabled: {{ .Values.config.redisTlsEnabled | quote }}
  ttnMqttEndpoint: {{ include "wasp-ingest-ttn.mqttBroker.endpoint" . }}
  kafkaBrokers: {{ include "wasp-ingest-ttn.kafka.brokers" . }}
  waspIngest: {{ .Values.config.waspIngestName }}
