apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wasp-ingest-ttn.fullname" . }}
  labels:
    {{- include "wasp-ingest-ttn.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: {{ include "wasp-ingest-ttn.fullname" . }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        name: {{ include "wasp-ingest-ttn.fullname" . }}
    spec:
      {{- include "wasp-ingest-ttn.imagePullSecrets" . | indent 6 }}
      {{- include "wasp-ingest-ttn.initContainers" . | indent 6 }}

      containers:
        - name: {{ include "wasp-ingest-ttn.fullname" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.config.waspIngestTtnPort }}
            initialDelaySeconds: 15
            timeoutSeconds: 3
            periodSeconds: 5
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "wasp-ingest-ttn.fullname" . }}-config
                  key: waspIngestTtnPort
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "wasp-ingest-ttn.fullname" . }}-config
                  key: redisHost
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "wasp-ingest-ttn.fullname" . }}-config
                  key: redisPort
            - name: REDIS_ENABLE_TLS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "wasp-ingest-ttn.fullname" . }}-config
                  key: redisTlsEnabled
            - name: REDIS_AUTH_ENABLED
              value: "true"
            - name: REDIS_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "wasp-ingest-ttn.fullname" . }}-secret
                  key: redisPassword
            - name: REDIS_AUTH_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "wasp-ingest-ttn.fullname" . }}-config
                  key: redisUsername
            - name: TTN_MQTT_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "wasp-ingest-ttn.fullname" . }}-config
                  key: ttnMqttEndpoint
            - name: TTN_APP_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "wasp-ingest-ttn.fullname" . }}-secret
                  key: ttnAppId
            - name: TTN_APP_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "wasp-ingest-ttn.fullname" . }}-secret
                  key: ttnAppKey
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name:  {{ include "wasp-ingest-ttn.fullname" . }}-config
                  key: kafkaBrokers
            - name: WASP_INGEST_NAME
              valueFrom:
                configMapKeyRef:
                  name:  {{ include "wasp-ingest-ttn.fullname" . }}-config
                  key: waspIngest
