apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wasp-ingest-ttn.fullname" . }}-secret
  labels:
    {{- include "wasp-ingest-ttn.labels" . | nindent 4 }}
data:
  redisPassword: {{ .Values.redis.auth.password | b64enc | quote }}
  ttnAppId: {{ .Values.config.ttnAppId | b64enc | quote }}
  ttnAppKey: {{ .Values.config.ttnAppKey | b64enc | quote }}
