apiVersion: v2
name: wasp-ingest-ttn
appVersion: '0.0.15'
description: A Helm chart for WASP-INGEST-TTN
version: '0.0.15'
type: application
maintainers:
  - name: digicatapult
    email: opensource@digicatapult.org.uk
    url: www.digicatapult.org.uk

dependencies:
  - name: redis
    version: '^14.1.0'
    repository: https://charts.bitnami.com/bitnami
  - name: kafka
    version: '12.7.3'
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
  - name: mosquitto
    version: '^0.7.0'
    repository: https://k8s-at-home.com/charts/
    condition: mosquitto.enabled
  - name: nginx
    alias: waspthingmock
    version: '^8.7.1'
    repository: https://charts.bitnami.com/bitnami
    condition: waspthingmock.enabled
